name: CI
on:
  pull_request:
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up SBT Cache
        uses: coursier/cache-action@v7
      - name: Install SDKs and Tools
        uses: jdx/mise-action@v3
      - name: Build and Test
        run: sbt "scalafmtCheckAll; scalafixAll --check; +test"
      - name: Update Dependency Graph
        if: github.ref == 'refs/heads/master'
        uses: scalacenter/sbt-dependency-submission@v3
        with:
          configs-ignore: scala-tool scala-doc-tool test
