name: CI
on:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up SBT Cache
        uses: coursier/cache-action@v8
      - name: Install SDKs and Tools
        uses: jdx/mise-action@v3
      - name: Build and Test
        run: sbt "scalafmtCheckAll; scalafixAll --check; coverage; test; coverageReport"
      - name: Upload Test Coverage Report
        uses: actions/upload-artifact@v6
        with:
          name: scoverage-report
          path: app/target/scala-*/scoverage-report
